project_id = "xvwksxpoktzuhcfqnpcx"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

  [functions.preview-transactional-email]
    verify_jwt = false

  [functions.send-welcome-email]
    verify_jwt = false

